<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    
    <property name="M_PI" value="3.1415926535897931" />
    <property name="LOWER_BASE_LENGTH" value="0.4705" />
    <property name="LUMBAR_LENGTH" value="0.291" />
    <property name="SHOULDER_TO_NECK_LENGTH" value="0.078" />
    <property name="HIP_TO_NECK_LENGTH" value="1" />
    <property name="NECK_LENGTH" value="0.14625" />
    <property name="SHOULDER_LENGTH" value="0.191" />
    <property name="HUMERAL_LENGTH" value="0.27325" />
    <property name="FOREARM_LENGTH" value="0.2308" />
    <property name="WRIST_TO_HAND_LENGTH" value="0.095" />
    
	<xacro:macro name="bert2_body" params="prefix">
		<link name="${prefix}table_link">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0.009"/>
                <geometry name="${prefix}table_link_visual_geom">
                    <box size="2 2 0.018"/>
                </geometry>
                <material name="Brown">
                    <color rgba="0.5 0.25 0 1"/>
                </material>
            </visual>
        </link>
        
        <joint name="${prefix}lower_base_joint" type="fixed">
            <parent link="${prefix}table_link"/>
            <child link="${prefix}lower_base_link"/>
        </joint>
        <link name="${prefix}lower_base_link">
            <visual>
                <origin xyz="0.0 0.0 ${LOWER_BASE_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}lower_base_link_visual_geom">
                    <box size="0.1 0.1 ${LOWER_BASE_LENGTH}" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${LOWER_BASE_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}lower_base_link_coll_geom">
                    <box size="0.08 0.08 ${LOWER_BASE_LENGTH}" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}hip_rotor_joint" type="revolute">
            <origin xyz="0.0 0.0 ${LOWER_BASE_LENGTH}" rpy="${M_PI} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}lower_base_link"/>
            <child link="${prefix}hip_rotor_link"/>
        </joint>
        <link name="${prefix}hip_rotor_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}hip_rotor_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}hip_rotor_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}hip_flexor_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/60}" upper="${M_PI/60}" velocity="5"/>
            <parent link="${prefix}hip_rotor_link"/>
            <child link="${prefix}hip_flexor_link"/>
        </joint>
        <link name="${prefix}hip_flexor_link">
            <visual>
                <origin xyz="0.0 ${LUMBAR_LENGTH/2} 0.0" rpy="0 0 0" />
                <geometry name="${prefix}hip_flexor_link_visual_geom">
                    <box size="0.08 ${LUMBAR_LENGTH} 0.08" />
                </geometry>
                <material name="Green">
                    <color rgba="0 1 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 ${LUMBAR_LENGTH/2} 0.0" rpy="0 0 0" />
                <geometry name="${prefix}hip_flexor_link_coll_geom">
                    <box size="0.05 ${LUMBAR_LENGTH} 0.05" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}neck_flexor_joint" type="revolute">
            <origin xyz="0.0 ${LUMBAR_LENGTH + SHOULDER_TO_NECK_LENGTH} 0.0" rpy="${M_PI} -0.0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/6}" upper="${M_PI/6}" velocity="5"/>
            <parent link="${prefix}hip_flexor_link"/>
            <child link="${prefix}neck_flexor_link"/>
        </joint>
        <link name="${prefix}neck_flexor_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}neck_flexor_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}neck_flexor_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        
        
        <joint name="${prefix}neck_rotor_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} -0.0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}neck_flexor_link"/>
            <child link="${prefix}neck_rotor_link"/>
        </joint>
        <link name="${prefix}neck_rotor_link">
            <visual>
                <origin xyz="0.0 0.0 ${NECK_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}neck_rotor_link_visual_geom">
                    <box size="0.02 0.02 ${NECK_LENGTH}" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${NECK_LENGTH}" rpy="0 0 0" />
                <geometry name="${prefix}neck_rotor_link_coll_geom">
                    <box size="0.012 0.012 ${NECK_LENGTH)*0.6}" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}head_joint" type="fixed">
            <origin xyz="0.0 0.0 ${NECK_LENGTH}" rpy="${M_PI/2} 0.0 ${M_PI/2}"/>
            <parent link="${prefix}neck_rotor_link"/>
            <child link="${prefix}head_link"/>
        </joint>
        <link name="${prefix}head_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}head_link_visual_geom">
                    <mesh filename="package://bert2_description/meshes/bert2_head.dae"  />
                </geometry>
                <material name="Blue" />
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.05" rpy="0 0 0" />
                <geometry name="${prefix}head_link_coll_geom">
                    <box size="0.012 0.012 0.06" />
                </geometry>
            </collision>
        </link>
        
        <!-- Right Arm -->
        <joint name="${prefix}right_shoulder_flex_joint" type="revolute">
            <origin xyz="0.0 ${LUMBAR_LENGTH} 0.0" rpy="0.0 -0.0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}hip_flexor_link"/>
            <child link="${prefix}right_shoulder_flex_link"/>
        </joint>
        <link name="${prefix}right_shoulder_flex_link">
            <visual>
                <origin xyz="0.0 0.0 ${SHOULDER_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_shoulder_flex_linkk_visual_geom">
                    <box size="0.0413 0.0413 ${SHOULDER_LENGTH}" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${SHOULDER_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_shoulder_flex_link_coll_geom">
                    <box size="0.02478 0.02478 ${SHOULDER_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}right_shoulder_abduction_joint" type="revolute">
            <origin xyz="0.0 0.0 ${SHOULDER_LENGTH}" rpy="${M_PI/2} ${M_PI/4} 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}right_shoulder_flex_link"/>
            <child link="${prefix}right_shoulder_abduction_link"/>
        </joint>
        <link name="${prefix}right_shoulder_abduction_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_shoulder_abduction_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_shoulder_abduction_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}right_humeral_rot_joint" type="revolute">
            <origin xyz="0.0 -0 0.0" rpy="${M_PI/2} -0.0 -${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}right_shoulder_abduction_link"/>
            <child link="${prefix}right_humeral_rot_link"/>
        </joint>
        <link name="${prefix}right_humeral_rot_link">
            <visual>
                <origin xyz="0.0 0.0 ${HUMERAL_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_humeral_rot_link_visual_geom">
                    <box size="0.053 0.053 ${HUMERAL_LENGTH}" />
                </geometry>
                <material name="Green">
                    <color rgba="0 1 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${HUMERAL_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_humeral_rot_link_coll_geom">
                    <box size="0.0318 0.0318 ${HUMERAL_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}right_elbow_flex_joint" type="revolute">
            <origin xyz="0.0 0.0 ${HUMERAL_LENGTH}" rpy="${M_PI/2} ${M_PI/4} ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI*(5.0/18.0)}" upper="${M_PI*(5.0/18.0)}" velocity="5"/>
            <parent link="${prefix}right_humeral_rot_link"/>
            <child link="${prefix}right_elbow_flex_link"/>
        </joint>
        <link name="${prefix}right_elbow_flex_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_elbow_flex_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_elbow_flex_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}right_wrist_pronation_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}right_elbow_flex_link"/>
            <child link="${prefix}right_wrist_pronation_link"/>
        </joint>
        <link name="${prefix}right_wrist_pronation_link">
            <visual>
                <origin xyz="0.0 0.0 ${FOREARM_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_wrist_pronation_link_visual_geom">
                    <box size="0.04086 0.04086 ${FOREARM_LENGTH}" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${FOREARM_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}right_wrist_pronation_link_coll_geom">
                    <box size="0.024516 0.024516 ${FOREARM_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}right_wrist_abduction_joint" type="revolute">
            <origin xyz="0.0 0.0 ${FOREARM_LENGTH}" rpy="${M_PI/2} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/18}" upper="${M_PI/18}" velocity="5"/>
            <parent link="${prefix}right_wrist_pronation_link"/>
            <child link="${prefix}right_wrist_abduction_link"/>
        </joint>
        <link name="${prefix}right_wrist_abduction_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_wrist_abduction_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Green">
                    <color rgba="0 1 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}right_wrist_abduction_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}right_wrist_flex_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} -0.0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}right_wrist_abduction_link"/>
            <child link="${prefix}right_wrist_flex_link"/>
        </joint>
        <link name="${prefix}right_wrist_flex_link">
            <visual>
                <origin xyz="${WRIST_TO_HAND_LENGTH/2} 0.02 0.02" rpy="0 0 0" />
                <geometry name="${prefix}right_wrist_flex_link_visual_geom">
                    <box size="${WRIST_TO_HAND_LENGTH} 0.04 0.04" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
        </link>
        
        <!-- Left Arm -->
        <joint name="${prefix}left_shoulder_flex_joint" type="revolute">
            <origin xyz="0.0 ${LUMBAR_LENGTH} 0.0" rpy="0.0 ${M_PI} -${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}hip_flexor_link"/>
            <child link="${prefix}left_shoulder_flex_link"/>
        </joint>
        <link name="${prefix}left_shoulder_flex_link">
            <visual>
                <origin xyz="0.0 0.0 ${SHOULDER_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_shoulder_flex_linkk_visual_geom">
                    <box size="0.0413 0.0413 ${SHOULDER_LENGTH}" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${SHOULDER_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_shoulder_flex_link_coll_geom">
                    <box size="0.02478 0.02478 ${SHOULDER_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        
        <joint name="${prefix}left_shoulder_abduction_joint" type="revolute">
            <origin xyz="0.0 0.0 ${SHOULDER_LENGTH}" rpy="${M_PI/2} ${M_PI/4} 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}left_shoulder_flex_link"/>
            <child link="${prefix}left_shoulder_abduction_link"/>
        </joint>
        <link name="${prefix}left_shoulder_abduction_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_shoulder_abduction_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_shoulder_abduction_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}left_humeral_rot_joint" type="revolute">
            <origin xyz="0.0 -0 0.0" rpy="0.0 -${M_PI/2} 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}left_shoulder_abduction_link"/>
            <child link="${prefix}left_humeral_rot_link"/>
        </joint>
        <link name="${prefix}left_humeral_rot_link">
            <visual>
                <origin xyz="0.0 0.0 ${HUMERAL_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_humeral_rot_link_visual_geom">
                    <box size="0.053 0.053 ${HUMERAL_LENGTH}" />
                </geometry>
                <material name="Green">
                    <color rgba="0 1 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${HUMERAL_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_humeral_rot_link_coll_geom">
                    <box size="0.0318 0.0318 ${HUMERAL_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}left_elbow_flex_joint" type="revolute">
            <origin xyz="0.0 0.0 ${HUMERAL_LENGTH}" rpy="${M_PI/2} -${M_PI/4} 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI*(5.0/18.0)}" upper="${M_PI*(5.0/18.0)}" velocity="5"/>
            <parent link="${prefix}left_humeral_rot_link"/>
            <child link="${prefix}left_elbow_flex_link"/>
        </joint>
        <link name="${prefix}left_elbow_flex_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_elbow_flex_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_elbow_flex_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}left_wrist_pronation_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="-${M_PI/2} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/2}" upper="${M_PI/2}" velocity="5"/>
            <parent link="${prefix}left_elbow_flex_link"/>
            <child link="${prefix}left_wrist_pronation_link"/>
        </joint>
        <link name="${prefix}left_wrist_pronation_link">
            <visual>
                <origin xyz="0.0 0.0 ${FOREARM_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_wrist_pronation_link_visual_geom">
                    <box size="0.04086 0.04086 ${FOREARM_LENGTH}" />
                </geometry>
                <material name="Red">
                    <color rgba="1 0 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 ${FOREARM_LENGTH/2}" rpy="0 0 0" />
                <geometry name="${prefix}left_wrist_pronation_link_coll_geom">
                    <box size="0.024516 0.024516 ${FOREARM_LENGTH*0.6}" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}left_wrist_abduction_joint" type="revolute">
            <origin xyz="0.0 0.0 ${FOREARM_LENGTH}" rpy="${M_PI/2} -0.0 0.0"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/18}" upper="${M_PI/18}" velocity="5"/>
            <parent link="${prefix}left_wrist_pronation_link"/>
            <child link="${prefix}left_wrist_abduction_link"/>
        </joint>
        <link name="${prefix}left_wrist_abduction_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_wrist_abduction_link_visual_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
                <material name="Green">
                    <color rgba="0 1 0 1"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry name="${prefix}left_wrist_abduction_link_coll_geom">
                    <box size="0.0 0.0 0.0" />
                </geometry>
            </collision>
        </link>
        <joint name="${prefix}left_wrist_flex_joint" type="revolute">
            <origin xyz="0.0 0.0 0.0" rpy="${M_PI/2} -0.0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <limit effort="100" lower="-${M_PI/4}" upper="${M_PI/4}" velocity="5"/>
            <parent link="${prefix}left_wrist_abduction_link"/>
            <child link="${prefix}left_wrist_flex_link"/>
        </joint>
        <link name="${prefix}left_wrist_flex_link">
            <visual>
                <origin xyz="${WRIST_TO_HAND_LENGTH/2} 0.02 0.02" rpy="0 0 0" />
                <geometry name="${prefix}left_wrist_flex_link_visual_geom">
                    <box size="${WRIST_TO_HAND_LENGTH} 0.04 0.04" />
                </geometry>
                <material name="Blue">
                    <color rgba="0 0 1 1"/>
                </material>
            </visual>
        </link>
        
		
	</xacro:macro>
</robot>

